# Generated by Django 3.2.5 on 2021-08-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210815_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='text',
        ),
        migrations.AddField(
            model_name='carousel',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
