# Generated by Django 3.2.5 on 2021-08-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210819_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='blog',
        ),
        migrations.AddField(
            model_name='page',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
