# Generated by Django 3.2.5 on 2021-08-22 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='animation',
            field=models.CharField(choices=[('bounceInLeft', 'Left'), ('bounceInRight', 'Right'), ('bounceInUp', 'Up'), ('bounceInDown', 'Down')], default='', max_length=40),
        ),
    ]
