# Generated by Django 3.2.5 on 2021-08-14 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsweredQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionBfi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('tendency', models.CharField(choices=[('O', 'Openness to Experience'), ('C', 'Conscientiousness'), ('E', 'Extraversion'), ('A', 'Agreableness'), ('N', 'Neuroticism')], max_length=1)),
                ('modifier', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionEpps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(max_length=40)),
                ('b', models.CharField(max_length=40)),
                ('tendency_a', models.CharField(choices=[('Ach', ''), ('Def', ''), ('Ord', ''), ('Exh', ''), ('Aut', ''), ('Aff', ''), ('Int', ''), ('Suc', ''), ('Dom', ''), ('Aba', ''), ('Nur', ''), ('Chg', ''), ('End', ''), ('Het', ''), ('Agg', '')], max_length=3)),
                ('tendency_b', models.CharField(choices=[('Ach', ''), ('Def', ''), ('Ord', ''), ('Exh', ''), ('Aut', ''), ('Aff', ''), ('Int', ''), ('Suc', ''), ('Dom', ''), ('Aba', ''), ('Nur', ''), ('Chg', ''), ('End', ''), ('Het', ''), ('Agg', '')], max_length=3)),
                ('consistency', models.CharField(choices=[('Ach', ''), ('Def', ''), ('Ord', ''), ('Exh', ''), ('Aut', ''), ('Aff', ''), ('Int', ''), ('Suc', ''), ('Dom', ''), ('Aba', ''), ('Nur', ''), ('Chg', ''), ('End', ''), ('Het', ''), ('Agg', '')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionMbti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('tendency', models.CharField(choices=[('E', 'Extroverted'), ('S', 'Sensing'), ('T', 'Thinking'), ('J', 'Judging')], max_length=1)),
                ('modifier', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionPapi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(max_length=40)),
                ('b', models.CharField(max_length=40)),
                ('tendency_a', models.CharField(choices=[('L', 'Leadership'), ('P', 'Need to Control Others'), ('I', 'Ease in Decision Making'), ('F', 'Need to Support Authority'), ('W', 'Need for Rules and Supervision'), ('T', 'Pace Type'), ('V', 'Vigorous Type'), ('R', 'Theoritical Type'), ('D', 'Interest in Details'), ('C', 'Organized Type'), ('X', 'Need to be Noticed'), ('B', 'Need to be Belonged to Group'), ('O', 'Need for Closeness and Affection'), ('S', 'Social Extension'), ('N', 'Need to Finish Task'), ('A', 'Need to Achieve'), ('G', 'Hard Intense Working'), ('Z', 'Need for Change'), ('K', 'Need to be Forceful'), ('E', 'Emotional Resistent')], max_length=1)),
                ('tendency_b', models.CharField(choices=[('L', 'Leadership'), ('P', 'Need to Control Others'), ('I', 'Ease in Decision Making'), ('F', 'Need to Support Authority'), ('W', 'Need for Rules and Supervision'), ('T', 'Pace Type'), ('V', 'Vigorous Type'), ('R', 'Theoritical Type'), ('D', 'Interest in Details'), ('C', 'Organized Type'), ('X', 'Need to be Noticed'), ('B', 'Need to be Belonged to Group'), ('O', 'Need for Closeness and Affection'), ('S', 'Social Extension'), ('N', 'Need to Finish Task'), ('A', 'Need to Achieve'), ('G', 'Hard Intense Working'), ('Z', 'Need for Change'), ('K', 'Need to be Forceful'), ('E', 'Emotional Resistent')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionTpa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('a', models.CharField(max_length=40)),
                ('b', models.CharField(max_length=40)),
                ('c', models.CharField(max_length=40)),
                ('d', models.CharField(max_length=40)),
                ('e', models.CharField(max_length=40)),
                ('key', models.CharField(max_length=2)),
                ('stream', models.CharField(choices=[('AG', 'Analogi'), ('SN', 'Sinonim'), ('AN', 'Antonim'), ('LG', 'Logika')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personality', models.CharField(max_length=4)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('additional_information', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Tester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('L', 'Laki-Laki'), ('P', 'Perempuan'), ('N', 'Tidak Menyampaikan')], max_length=1)),
                ('type', models.CharField(blank=True, choices=[('MBTI', 'Myers-Briggs Type Indicator'), ('BFI', 'Big Five Inventory'), ('PAPI', 'PAPI Kostick'), ('TPA', 'Tes Potensi Akademik')], max_length=30, null=True)),
                ('education', models.CharField(blank=True, choices=[('S3', 'Doktoral/S3'), ('S2', 'Magister/S2'), ('S1', 'Sarjana/S1'), ('D4', 'Diploma-4/D4/STr'), ('D3', 'Diploma-3/D3'), ('SMK', 'Sekolah Menengah Kejuruan/SMK'), ('SMA', 'Sekolah Menengah Atas/SMA/MA'), ('SMP', 'Sekolah Menengah Pertama/SMP/MTs'), ('SD', 'Sekolah Dasar/SD/MI'), ('NA', 'Tidak Lulus Sekolah Dasar')], max_length=30, null=True)),
                ('finished', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.BooleanField(default=False)),
                ('type', models.CharField(blank=True, choices=[('MBTI', 'Myers-Briggs Type Indicator'), ('BFI', 'Big Five Inventory'), ('PAPI', 'PAPI Kostick'), ('TPA', 'Tes Potensi Akademik')], max_length=5, null=True)),
                ('answered_questions', models.ManyToManyField(to='test_core.AnsweredQuestion')),
                ('tester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test_core.tester')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='answeredquestion',
            name='question_bfi',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_core.questionbfi'),
        ),
        migrations.AddField(
            model_name='answeredquestion',
            name='question_epps',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_core.questionepps'),
        ),
        migrations.AddField(
            model_name='answeredquestion',
            name='question_mbti',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_core.questionmbti'),
        ),
        migrations.AddField(
            model_name='answeredquestion',
            name='question_papi',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_core.questionpapi'),
        ),
        migrations.AddField(
            model_name='answeredquestion',
            name='question_tpa',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_core.questiontpa'),
        ),
        migrations.AddField(
            model_name='answeredquestion',
            name='tester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test_core.tester'),
        ),
    ]
