# Generated by Django 3.2.5 on 2021-08-17 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_core', '0002_auto_20210817_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testattempt',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
