# Generated by Django 3.2.5 on 2021-08-15 06:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image_caption',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
    ]
