# Generated by Django 3.2.5 on 2021-08-15 04:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0002_auto_20210815_1152'),
        ('test_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EnrolledItem',
            new_name='EnrolledProduct',
        ),
        migrations.RenameField(
            model_name='enrolledproduct',
            old_name='item',
            new_name='product',
        ),
    ]
