# Generated by Django 3.2.5 on 2021-08-16 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
        ('shop', '0002_auto_20210815_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_profile.address'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
