# Generated by Django 3.2.5 on 2021-08-16 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210816_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
