# Generated by Django 3.2.5 on 2021-08-17 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_coupon_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, choices=[('MBTI', 'Myers-Briggs Type Indicator'), ('BFI', 'Big Five Inventory'), ('PAPI', 'PAPI Kostick'), ('EPPS', 'Edward Personal Preference Schedule'), ('DISC', 'Dominant, Influencing, Steadiness, Conscientiousness'), ('MSDT', 'Management Style Diagnostic Test'), ('PF16', 'Personality Factor Sixteen'), ('TPA', 'Tes Potensi Akademik')], max_length=30, null=True),
        ),
    ]
