# Generated by Django 3.2.5 on 2021-08-20 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_product_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='address',
            new_name='shipping_address',
        ),
    ]
