# Generated by Django 3.2.5 on 2021-08-20 01:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0006_rename_address_cart_shipping_address'),
        ('user_profile', '0003_auto_20210816_0922'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='ShippingAddress',
        ),
    ]
